#define CACHE_SIZE 999
#define DISK_SIZE NO_PLATTERS*(NO_SECTORS_MIN+NO_SECTORS_MAX)*NO_TRACKS/2
#define NO_PLATTERS 3
#define NO_TRACKS 100
#define NO_SECTORS_MIN 101
#define NO_SECTORS_MAX 200
#define DATA_SIZE 512
