
#define DISK_SIZE NO_PLATTERS*PLATTER_SIZE
#define PLATTER_SIZE (NO_SECTORS_MIN+NO_SECTORS_MAX)*NO_TRACKS/2
#define NO_PLATTERS 3l
#define NO_TRACKS 100l
#define NO_SECTORS_MIN 101l
#define NO_SECTORS_MAX 200l
#define DATA_SIZE 512l
#define TOTAL_DISK 4l
